project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "NYC 311 Service Requests Analysis"
  author:
    - Shweta Tripathi (sst2166)
    - Hardik Saurabh Gupta (hg2770)
  repo-url: https://github.com/Shweta-3001/Group-15-NYC-311-Request-Edav-Project
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - interactive_plot.qmd
    - conclusion.qmd
format:
  html:
    theme: superhero
    code-fold: true



